### PR TITLE
Bugs/podman macos

### LINKED ISSUE #201: cannot create directory '/app/fyne-cross/bin/windows-amd64': Permission denied
### Describe the bug:

Trying to create a cross-compile build fails early with permission errors

### To Reproduce:
Steps to reproduce the behaviour:
1. Run any fyne-cross command
1. See error `could not create the "bin" dir /app/fyne-cross/bin/windows-amd64: exit status 1`

### Device and debug info (please complete the following information):

<summary>Device info</summary>

 - **OS:** Linux 
 - **Version:** Ubuntu 23.04 (running in VMWare on a macOS host)
 - **Go version:** go version go1.20.3 linux/amd64
 - **fyne-cross version:** v1.4.0
 - **Fyne version:** v2.3.5

<details><summary>Debug info</summary><br><pre>
paul@kubuntu:~/src/personal/mastotool$ fyne-cross windows -debug -pull --no-cache
[i] Target: windows/amd64
&command.localContainerImage{baseContainerImage:command.baseContainerImage{arch:"amd64", os:"windows", id:"windows-amd64", env:map[string]string{"CC":"zig cc -target x86_64-windows-gnu -Wdeprecated-non-prototype -Wl,--subsystem,windows", "CXX":"zig c++ -target x86_64-windows-gnu -Wdeprecated-non-prototype -Wl,--subsystem,windows", "GOARCH":"amd64", "GOOS":"windows"}, tags:[]string(nil), mount:[]command.containerMountPoint{command.containerMountPoint{name:"project", localHost:"/home/paul/src/personal/mastotool", inContainer:"/app"}}, DockerImage:"docker.io/fyneio/fyne-cross-images:windows"}, runner:(*command.localContainerEngine)(0xc0000a8090)}
[i] Checking for a newer version of the docker image: docker.io/fyneio/fyne-cross-images:windows
/usr/local/bin/docker pull docker.io/fyneio/fyne-cross-images:windows
windows: Pulling from fyneio/fyne-cross-images
Digest: sha256:6bec023193006495217fd8f8c9da305ed20865f3698bc6ce013bd0e49d89c795
Status: Image is up to date for fyneio/fyne-cross-images:windows
docker.io/fyneio/fyne-cross-images:windows

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview docker.io/fyneio/fyne-cross-images:windows
[✓] Image is up to date
[i] Cleaning target directories...
/usr/local/bin/docker run --rm -t -w /app -v /home/paul/src/personal/mastotool:/app:z --platform linux/amd64 -u 1000:1000 --entrypoint fixuid -v /tmp/ssh-XXXXXXQKcu6A/agent.1448:/tmp/ssh-agent -e SSH_AUTH_SOCK=/tmp/ssh-agent -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e GOOS=windows -e GOARCH=amd64 -e CC=zig cc -target x86_64-windows-gnu -Wdeprecated-non-prototype -Wl,--subsystem,windows -e CXX=zig c++ -target x86_64-windows-gnu -Wdeprecated-non-prototype -Wl,--subsystem,windows docker.io/fyneio/fyne-cross-images:windows rm -rf /app/fyne-cross/bin/windows-amd64
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: runtime UID '1000' already matches container user 'docker' UID
fixuid: runtime GID '1000' already matches container group 'docker' GID
/usr/local/bin/docker run --rm -t -w /app -v /home/paul/src/personal/mastotool:/app:z --platform linux/amd64 -u 1000:1000 --entrypoint fixuid -v /tmp/ssh-XXXXXXQKcu6A/agent.1448:/tmp/ssh-agent -e SSH_AUTH_SOCK=/tmp/ssh-agent -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e CC=zig cc -target x86_64-windows-gnu -Wdeprecated-non-prototype -Wl,--subsystem,windows -e CXX=zig c++ -target x86_64-windows-gnu -Wdeprecated-non-prototype -Wl,--subsystem,windows -e GOOS=windows -e GOARCH=amd64 docker.io/fyneio/fyne-cross-images:windows mkdir -p /app/fyne-cross/bin/windows-amd64
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: runtime UID '1000' already matches container user 'docker' UID
fixuid: runtime GID '1000' already matches container group 'docker' GID
mkdir: cannot create directory '/app/fyne-cross/bin/windows-amd64': Permission denied
[✗] could not create the "bin" dir /app/fyne-cross/bin/windows-amd64: exit status 1

### PR DESCRIPTION
**Pull request by Bluebugs**
### Description:
Trying to figure out a fix for some configuration of MacOS host.

Fixes #201 

### Checklist:
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

### CODE REVIEW

File: internal/command/docker.go [hunk 1]
```diff
@@ -104,7 +104,7 @@ func (i *localContainerImage) cmd(vol volume.Volume, opts options, cmdArgs []str
 	}
 
 	mountFormat := "%s:%s:z"
-	if runtime.GOOS == darwinOS && runtime.GOARCH == string(ArchArm64) {
+	if runtime.GOOS == darwinOS {
 		// When running on darwin with a Arm64, we rely on going through a VM setup that doesn't allow the :z
```
Comment (andydotxyz) [inline internal/command/docker.go:108]: The comment is now out of date

**Review by andydotxyz — APPROVED** [review]
Looks good to me
